name: App Release

on:
  release:
    types: [ published ]

permissions:
  contents: write

jobs:
  zip-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Build deployment
        run: |
          npm install
          ./scripts/build.sh

      - name: Build zip
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          ZIP_NAME="${REPO_NAME}-${TAG_NAME}.zip"
          zip -r "$ZIP_NAME" ./build
          shasum -a 256 "$ZIP_NAME" >> "${ZIP_NAME}.sha256"
          echo "ZIP_NAME=${ZIP_NAME}" >> $GITHUB_ENV

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ env.ZIP_NAME }}
            ${{ env.ZIP_NAME }}.sha256
          overwrite_files: true